# Ridge Regression (Discesa del gradiente)

In [2]:
import graphlab

# Carica il dataset delle case



In [3]:
sales = graphlab.SFrame('kc_house_data.csv')

In [3]:
import numpy as np 

In [4]:
len(sales)

21613

In [5]:
def get_numpy_data(data_sframe, features, output):
    data_sframe['constant'] = 1 # aggiungiamo una colonna costante all' SFrame
    #aggiungi la colonna costante prima delle feature considerate:
    features = ['constant'] + features # combino le due liste
    #seleziono le colonne del SFrame contenute all'interno della lista di feature
    features_sframe = data_sframe[features]
    #Converto feature_sframe in una matrice numpy
    feature_matrix = features_sframe.to_numpy()
    #assegna la colonna corrispondente all'output a SArray output_sarray
    output_sarray = data_sframe[output]
    #converto output_sarray in un array_numpy
    output_array = output_sarray.to_numpy()
    return(feature_matrix, output_array)

In [6]:
def predict_output(feature_matrix, weights):
    predictions = []
    for col in range(feature_matrix.shape[0]):
        predictions.append(np.dot(feature_matrix[col,], weights))
    return(predictions)

# Calcolo della derivata

In [7]:
def feature_derivative(errori, feature):
    # Nel caso della feature w[0] la derivata non considera l2_penalty
        derivative = 2 * np.dot(errori, feature)
        return derivative

To test your feature derivartive run the following:

In [8]:
from math import sqrt


# Discesa del gradiente

In [11]:
def gradient_descent_RR(feature_matrix, output, initial_weights, step_size, l2_penalty, tolerance):
    converged = False
    iterations=0
    weights = np.array(initial_weights) # trasformo i pesi iniziali in un array 
    while not converged and iterations <1000:
    #calcolo le predizioni basandomi sulle feature matrix e sui pesi
        predictions = predict_output(feature_matrix, weights)
        # calcolo gli errori
        iterations=iterations+1
        errors = predictions - output
        gradient_cost=0
        #fino a che non ho raggiunto il grado di tolleranza, aggiorno i pesi delle features
        for i in range(len(weights)): # loop su ogni feature
            # calcolo la derivata per la feature[i]
            derivative = feature_derivative(errors,feature_matrix[:,i])
            if(i==0):
            #sottraggo lo step size * derivata del peso corrente
                weights[i] -= step_size * derivative
                gradient_cost = gradient_cost + derivative**2
            else:
                weights[i] = (1-2*step_size*l2_penalty)*weights[i]- step_size*derivative
                gradient_cost = gradient_cost+((derivative + 2*l2_penalty*weights[i])**2)
                
        #calcolo il costo della ridge
        gradient_magnitude = sqrt(gradient_cost)
        print gradient_magnitude
        if gradient_magnitude < tolerance:
            converged = True;
    return weights

# Visualizzare gli effetti di L2 penalty

In [12]:
simple_features = ['sqft_living']
my_output = 'price'

Splitta in train e test

In [13]:
train_data,test_data = sales.random_split(.8,seed=0)

In [49]:
(simple_feature_matrix, output) = get_numpy_data(train_data, simple_features, my_output)
(simple_test_feature_matrix, test_output) = get_numpy_data(test_data, simple_features, my_output)

In [15]:
len(output)

17384

Alcuni parametri per l'ottimizzazione 

In [77]:
initial_weights = np.array([-45000, 1.])
step_size = 1e-11
tolerance = 1e7

In [78]:
simple_weights_0_penalty = gradient_descent_RR(simple_feature_matrix, output, initial_weights, step_size, 0.00000000001, tolerance)

5.04068938367e+13
4.03027988542e+13
3.22240763484e+13
2.57647390759e+13
2.06001802029e+13
1.64708605487e+13
1.31692657318e+13
1.05294777648e+13
8.41883702987e+12
6.73127561679e+12
5.38198699754e+12
4.30316416839e+12
3.44059208403e+12
2.75092314063e+12
2.19949878998e+12
1.75860781266e+12
1.40609372138e+12
1.12424131127e+12
8.98886401925e+11
7.18704032205e+11
5.74639336869e+11
4.59452504362e+11
3.67354948114e+11
2.93718407533e+11
2.34842359907e+11
1.87768054733e+11
1.50129824989e+11
1.20036203167e+11
95974867662.6
76736642735.0
61354732718.0
49056136775.8
39222802603.8
31360566894.2
25074321707.6
20048158761.1
16029493807.7
12816373295.4
10247325414.8
8193245512.74
6550908080.9
5237779272.34
4187869254.49
3348415963.36
2677233604.37
2140592652.13
1711524810.44
1368467750.49
1094181519.83
874882167.583
699549047.123
559370985.257
447303485.796
357714714.743
286102475.899
228867952.468
183134841.816
146604789.197
117441846.166
94180129.3082
75650005.6649
60919035.3233
49244599.5237
4003566

In [74]:
simple_weights_high_penalty = gradient_descent_RR(simple_feature_matrix, output, initial_weights, step_size, 1000000000, tolerance)

4.93967961244e+13
4.04831116505e+13
3.31779074364e+13
2.71909321325e+13
2.22843104868e+13
1.82630919436e+13
1.49675049534e+13
1.22666087988e+13
1.00530911507e+13
8.23900421114e+12
6.75227046987e+12
5.5338188015e+12
4.53523755364e+12
3.71685093914e+12
3.04614274223e+12
2.49646427037e+12
2.04597565461e+12
1.67677799537e+12
1.37420231076e+12
1.126226597e+12
9.22998278264e+11
7.56442633192e+11
6.19942078708e+11
5.08073129637e+11
4.16391021804e+11
3.41253002375e+11
2.79673705238e+11
2.29206426339e+11
1.87846020632e+11
1.53949123681e+11
1.26168967006e+11
1.03401758388e+11
84742935568.0
69451116347.5
56918751608.9
46647876381.5
38230434345.7
31331955173.4
25678375021.5
21045037679.9
17247878211.3
14135999949.0
11585788755.0
9495891858.83
7783300585.59
6379942538.94
5230086588.88
4288018844.11
3516335881.17
2884348864.42
2366973443.29
1943623103.29
1597499560.84
1314814475.54
1084347426.2
896886475.431
744961287.982
622425445.336
524296826.898
446426761.637
385401892.872
338278515.318
30254441

KeyboardInterrupt: 

Calcolo dell'RSS

In [21]:
predictions_1 = predict_output(simple_test_feature_matrix, initial_weights)
residuals_1 = [(predictions_1[i] - test_output[i]) ** 2 for i in range(len(predictions_1))]
print sum(residuals_1)

1.98730283193e+15


In [22]:
predictions_2 = predict_output(simple_test_feature_matrix, simple_weights_0_penalty)
residuals_2 = [(predictions_2[i] - test_output[i]) ** 2 for i in range(len(predictions_2))]
print sum(residuals_2)

2.75353149057e+14


In [23]:
predictions_3 = predict_output(simple_test_feature_matrix, simple_weights_high_penalty)
residuals_3 = [(predictions_3[i] - test_output[i]) ** 2 for i in range(len(predictions_3))]
print sum(residuals_3)

2.75353149117e+14


In [69]:
simple_weights_0_penalty

array([-44999.89564297,    281.1083398 ])

In [70]:
simple_weights_high_penalty

array([-44999.89413182,    281.07709939])

# Multiple regression con L2 penalty

Consideriamo un modello con 2 feature: `['sqft_living', 'sqft_living15']`.

In [26]:
model_features = ['sqft_living', 'bedrooms'] 
my_output = 'price'
(feature_matrix, train_output) = get_numpy_data(train_data, model_features, my_output)
(test_feature_matrix, test_output) = get_numpy_data(test_data, model_features, my_output)

Definiamo nuovamente i pesi

In [59]:
initial_weights = np.array([0.0,0.0,0.0])
step_size = 1e-12
tolerance = 18e8

In [61]:
multiple_weights_0_penalty = gradient_descent_RR(feature_matrix, train_output, initial_weights, step_size, 0, tolerance)

4.73325646e+13
3.88148181656e+13
3.18298854545e+13
2.6101928495e+13
2.14047478239e+13
1.75528497731e+13
1.43941212458e+13
1.18038227055e+13
9.67966215794e+12
7.93775559723e+12
6.50931439039e+12
5.33792878496e+12
4.37734026378e+12
3.5896147765e+12
2.94364470765e+12
2.41392042373e+12
1.97952288685e+12
1.623297553e+12
1.33117693184e+12
1.09162505543e+12
8.95181918033e+11
7.34089896356e+11
6.01987397763e+11
4.93657638244e+11
4.04822629393e+11
3.31974238821e+11
2.72235652511e+11
2.23247768202e+11
1.83076033432e+11
1.50134049232e+11
1.23120922541e+11
1.00969893363e+11
82806207923.5
67912574203.7
55700835649.7
45688744398.7
37480916706.9
30753218355.1
25239963148.4
20723418512.3
17025202936.7
13999234112.7
11525946798.4
9507547889.37
7864114529.87
6530370838.28
5453001777.2
4588382269.59
3900622313.43
3359864284.62
2940824010.48
2621631826.67
2383061497.46
2208182095.86
2082337603.21
1993247532.16
1931026797.47
1888032245.37
1858560301.95
1838475515.72
1824844697.99
1815620763.09
1809391442.8

In [63]:
multiple_weights_high_penalty = gradient_descent_RR(feature_matrix, train_output, initial_weights, step_size, 10000000, tolerance)

4.73316179488e+13
3.88130952371e+13
3.18276963144e+13
2.60994967485e+13
2.14022316932e+13
1.75503583889e+13
1.43917271923e+13
1.18015716401e+13
9.67758015232e+12
7.93585470798e+12
6.50759685915e+12
5.33639018062e+12
4.37597181162e+12
3.58840506507e+12
2.94258092203e+12
2.41298922025e+12
1.97871099845e+12
1.62259219382e+12
1.3305660537e+12
1.09109749644e+12
8.94727473757e+11
7.33699336719e+11
6.01652446831e+11
4.93370929727e+11
4.04577647261e+11
3.3176524983e+11
2.72057635471e+11
2.23096343351e+11
1.82947394161e+11
1.50024897598e+11
1.23028409427e+11
1.00891563685e+11
82739951014.7
67856579273.2
55653552101.3
45648846694.1
37447273417.9
30724865028.3
25216078604.3
20703304212.0
17008265068.9
13984968078.8
11513923800.7
9497403359.57
7855538167.51
6523098065.3
5446806455.89
4583070576.23
3896027704.35
3355843521.21
2937254200.08
2618408360.65
2380096632.84
2205403802.73
2079688295.9
1990682463.72
1928512135.04
1885543015.66
1856078430.9
1835988121.41
1822342703.96
1813097827.59
180684316

In [42]:
predictions_4 = predict_output(test_feature_matrix, initial_weights)
residuals_4 = [(predictions_4[i] - test_output[i]) ** 2 for i in range(len(predictions_4))]
print sum(residuals_4)

1.78427328614e+15


In [43]:
predictions_5 = predict_output(test_feature_matrix, multiple_weights_0_penalty)
residuals_5 = [(predictions_5[i] - test_output[i]) ** 2 for i in range(len(predictions_5))]
print sum(residuals_5)

2.75723729958e+14


In [44]:
predictions_6 = predict_output(test_feature_matrix, multiple_weights_high_penalty)
residuals_6 = [(predictions_6[i] - test_output[i]) ** 2 for i in range(len(predictions_6))]
print sum(residuals_6)

2.75723729958e+14


In [47]:
first = test_data[0]
a, b, c= multiple_weights_0_penalty
p_0 = a + b * first['sqft_living'] + c * first['bedrooms']
print p_0

d, e, f = multiple_weights_high_penalty
p_high = d + e * first['sqft_living'] + f * first['bedrooms']
print p_high

387465.476465
270453.530305


In [48]:
first['price']

310000.0

In [64]:
multiple_weights_0_penalty

array([  8.76903118e-02,   2.63023430e+02,   2.62224338e-01])

In [65]:
multiple_weights_high_penalty

array([  8.83417666e-02,   2.62993981e+02,   2.65808136e-01])