# Unita: One-hot encoding

Codifica One-hot encoding usando scikit-learn

In [1]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# Problema #1

Implementa una funzione che, dato un vettore in input, restituisca la relativa rappresentazione one-hot.

Confronta il risultato con la funzione OneHotEncoder in sklearn.preprocessing.

In [2]:
# vettore in input

v = ['rosso', 'rosso', 'bianco', 'nero', 'bianco', 'nero', 'nero']

In [3]:
# da list a array

a = array(v)

In [4]:
# integer encoder 

le = LabelEncoder()
iv = le.fit_transform(a)
print(iv)

[2 2 0 1 0 1 1]


In [11]:
# one-hot encoder

oe = OneHotEncoder(sparse=False)

# converto l'array N-dim in matrice N-dim x 1
iv = iv.reshape(len(iv), 1)
bv = oe.fit_transform(iv)
print('   B   N   R')
print(bv)


   B   N   R
[[ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]]
